# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSejam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryinfo',
            name='first_log_in',
            field=models.BooleanField(default=False),
        ),
    ]
