# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSejam', '0003_permanentlyinfo_first_log_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='approvec',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainSejam.Union'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='union',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
