# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSejam', '0004_auto_20160926_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategory',
            old_name='approvec',
            new_name='approved',
        ),
    ]
