# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSejam', '0005_auto_20160926_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentlyinfo',
            name='b_sheba_num',
            field=models.CharField(max_length=50),
        ),
    ]
